FA.JustBlog/Areas/Admin/Controllers/CategoryManagementController.cs
using AutoMapper;
using FA.JustBlog.Areas.Admin.ViewModels;
using FA.JustBlog.Core.Common;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers 
{
    [Authorize(Roles = "Contributor")]
    public class CategoryManagementController : Controller
    {
        private readonly IPostService _postService;
        private readonly ICatgoryService _categoryService;
        private readonly ITagService _tagService;

        public CategoryManagementController(IPostService postService, ICatgoryService categoryService, ITagService tagService)
        {
            _postService = postService;
            _categoryService = categoryService;
            _tagService = tagService;
        }

        public async Task<ActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page, int? pageSize)
        {
            List<SelectListItem> items = new List<SelectListItem>();
            items.Add(new SelectListItem { Text = "5", Value = "5" });
            items.Add(new SelectListItem { Text = "10", Value = "10" });
            items.Add(new SelectListItem { Text = "20", Value = "20" });
            items.Add(new SelectListItem { Text = "25", Value = "25" });
            items.Add(new SelectListItem { Text = "50", Value = "50" });
            items.Add(new SelectListItem { Text = "100", Value = "100" });
            items.Add(new SelectListItem { Text = "200", Value = "200" });
            foreach (var item in items)
            {
                if (item.Value == pageSize.ToString()) item.Selected = true;
            }

            ViewBag.size = items;
            ViewData["CurrentSize"] = pageSize ?? 10;
            ViewData["CurrentSort"] = sortOrder;
            ViewData["NameSortParm"] = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewData["PosteCountSortParm"] = sortOrder == "PostCount" ? "post_count_desc" : "PostCount";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;
            

            Expression<Func<Category, bool>> filter = null;
            Func<IQueryable<Category>, IOrderedQueryable<Category>> orderBy = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = b => b.Name.Contains(searchString);
            }

            switch (sortOrder)
            {
                case "name_desc":
                    orderBy = b => b.OrderByDescending(s => s.Name);
                    break;
                case "PostCount":
                    orderBy = b => b.OrderBy(s => s.Posts.Count());
                    break;
                case "post_count_desc":
                    orderBy = b => b.OrderByDescending(s => s.Posts.Count());
                    break;
                default:
                    orderBy = b => b.OrderBy(s => s.Name);
                    break;
            }

            var response = await _categoryService.GetAllAsyncPagination(filter: filter, orderBy: orderBy, page: page ?? 1, pageSize: pageSize ?? 10);
            if (response.Status != 200)
            {
                return HttpNotFound();
            }
            else
            {
                return View(response.Data);
            }
        }

        public ActionResult CreateCategory()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult CreateCategory(CategoryEditViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                Category category = Mapper.Map<Category>(categoryViewModel);
                var response = _categoryService.Add(category);

                if(response.Status == 200)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(categoryViewModel);
                }
            }
            else
            {
                return View(categoryViewModel);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        [Authorize(Roles = "Administrators")]
        public string DeleteCategory(int Id)
        {
            var response = _categoryService.Delete(Id);

            return response.MessageText;
        }

        public ActionResult EditCategory(int Id)
        {
            var response = _categoryService.Find(Id);
            if(response.Status == 200)
            {
                var data = Mapper.Map<CategoryEditViewModel>(response.Data);
                return View(data);
            }

            return HttpNotFound(response.MessageText);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public ActionResult EditCategory(CategoryEditViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                var category = Mapper.Map<Category>(categoryViewModel);
                _categoryService.DetachEntity(category);
                var response = _categoryService.Update(category);
                if (response.Status == 200)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View(categoryViewModel);
                }
            }
            return View(categoryViewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateInput(false)]
        public JsonResult QuickAddCategory(CategoryEditViewModel categoryViewModel)
        {
            if (ModelState.IsValid)
            {
                Category category = Mapper.Map<Category>(categoryViewModel);
                var response = _categoryService.Add(category);

                List<SelectListItem> cateList = new List<SelectListItem>();
                if (response.Status == 200)
                {
                    SelectListItem newCategory = new SelectListItem()
                    {
                        Value = category.Id.ToString(),
                        Text = category.Name
                    };
                    cateList.Add(newCategory);
                    return Json(cateList, JsonRequestBehavior.AllowGet);
                }
                else
                {
                    return Json(null, JsonRequestBehavior.AllowGet);
                }
            }
            else
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

FA.JustBlog/Areas/Admin/Views/CategoryManagement/CreateCategory.cshtml
@model CategoryEditViewModel

@{
    ViewBag.Title = "Create Category";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Create Category</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @name = "title", @id = "title" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control", @name = "slug", @id = "slug", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Description, new { @class = "form-control", @rows = "3", @style = "width:100%", @id = "description" } )
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

FA.JustBlog/Areas/Admin/Views/CategoryManagement/EditCategory.cshtml
@model CategoryEditViewModel

@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}



<div class="container">
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <h4>Edit Category</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control", @name = "title", @id = "title" } })
                    @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.UrlSlug, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.UrlSlug, new { htmlAttributes = new { @class = "form-control", @name = "slug", @id = "slug", @readonly = "readonly" } })
                    @Html.ValidationMessageFor(model => model.UrlSlug, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

FA.JustBlog/Areas/Admin/Views/CategoryManagement/Index.cshtml
@model PaginationList<Category>

@{
    ViewBag.Title = "ListCategory";
    Layout = "~/Areas/Admin/Views/Shared/_DashboardLayout.cshtml";
}

<div class="container-fluid">
    <h2>List Category</h2>
    <hr />
    <div class="row col-md-12">
        <div class="col-md-4">
            <a href="@Url.Action("CreateCategory", "CategoryManagement")" class="btn btn-primary float-left">Create Category</a>
        </div>
        <div class="col-md-8">
            <form action="@Url.Action("Index", "CategoryManagement")" method="get" class="form-inline float-right">
                <div class="form-group mx-sm-3 mb-2">
                    <input type="text" class="form-control mr-1" id="inputSearch" name="searchString" value="@ViewData["CurrentFilter"]" placeholder="Input ...">
                    <button type="submit" class="btn-sm btn-primary mr-5"><i class="fa fa-search"></i></button>
                    <a href="@Url.Action("Index", "CategoryManagement")" class="btn btn-primary ml-5"><i class="fa fa-refresh"></i></a>
                </div>
            </form>
        </div>
    </div>
    @if (!Model.Any())
    {
        <div class="row">
            <table class="table">
                <tr>
                    <td colspan="3" class="text-center">Don't have result.</td>
                </tr>
            </table>
        </div>
    }
    else
    {
        <div class="row col-md-12 mt-4 d-flex justify-content-center">
            <div class="row col-md-8">
                <div class="col-md-4">
                    @using (Html.BeginForm("Index", "CategoryManagement", FormMethod.Get))
                {
                        <p>
                            Page Size: @Html.DropDownList("pageSize", new SelectList(ViewBag.size, "Value", "Text", ViewData["CurrentSize"]), new { @onchange = "this.form.submit();" })
                        </p>
                    }
                </div>
                <table class="table-striped table-bordered table-responsive" style="font-size: 16px" id="listcate">
                    <tr>
                        <th style="width:15%; text-align: center">
                            <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder = ViewData["NameSortParm"], currentFilter = ViewData["CurrentFilter"], pageSize = ViewData["CurrentSize"] })">
                                Name
                                @{
                                    if (ViewData["NameSortParm"].ToString() == "")
                                    {
                                        <i class='fa fa-fw fa-sort-asc'></i>
                                    }
                                    else if (ViewData["NameSortParm"].ToString() == "name_desc")
                                    {
                                        <i class='fa fa-fw fa-sort-desc'></i>
                                    }
                                    else
                                    {
                                        <i class='fa fa-fw fa-sort'></i>
                                    }
                                }
                            </a>
                        </th>
                        <th style="width:32%; text-align: center">
                            Description
                        </th>
                        <th style="width:10%; text-align: center">
                            <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder = ViewData["PosteCountSortParm"], currentFilter = ViewData["CurrentFilter"], pageSize = ViewData["CurrentSize"] })">
                                Post Number
                                @{
                                    if (ViewData["PosteCountSortParm"].ToString() == "PostCount")
                                    {
                                        <i class='fa fa-fw fa-sort-asc'></i>
                                    }
                                    else if (ViewData["PosteCountSortParm"].ToString() == "post_count_desc")
                                    {
                                        <i class='fa fa-fw fa-sort-desc'></i>
                                    }
                                    else
                                    {
                                        <i class='fa fa-fw fa-sort'></i>
                                    }
                                }
                            </a>
                        </th>
                        <th style="width: 8%"></th>
                    </tr>

                    @foreach (var item in Model)
                {
                        <tr>
                            <td style="padding-left: 5px">
                                @Html.DisplayFor(modelItem => item.Name)
                            </td>
                            <td style="padding-left: 5px">
                                @Html.DisplayFor(modelItem => item.Description)
                            </td>
                            <td style="text-align: center">
                                @item.Posts.Count()
                            </td>
                            <td style="text-align: center">
                                <button class="btn-sm btn-primary" onclick="location.href='@Url.Action("EditCategory", "CategoryManagement", new { Id = @item.Id})'"><i class="fa fa-edit"></i></button> |
                                <button class="btn-sm btn-danger" onclick="DeleteCategory(@item.Id)" id="delete_@item.Id"><i class="fa fa-remove"></i></button>
                            </td>
                        </tr>
                    }
                </table>
            </div>
            <div class="row col-md-12 d-flex justify-content-center">
                <nav class="mt-4" aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        @{
                            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                            var preBgDisabled = !Model.HasPreviousPage ? "#e6e6e6" : "";
                            var nextBgDisabled = !Model.HasNextPage ? "#e6e6e6" : "";

                            ViewBag.PageRange = 3;
                        }
                        <li class="page-item @prevDisabled">
                            <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=1, currentFilter=ViewData["CurrentFilter"], pageSize = ViewData["CurrentSize"] })"
                               class="page-link" style="background-color:@preBgDisabled"><<</a>
                        <li class="page-item @prevDisabled">
                            <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex - 1 <= 0 ? 1 : Model.PageIndex - 1), currentFilter=ViewData["CurrentFilter"], pageSize = ViewData["CurrentSize"] })"
                               class="page-link" style="background-color:@preBgDisabled"><</a>
                        </li>
                        @for (int i = 1; i <= Model.TotalPages; i++)
                {
                    if (i >= Model.PageIndex - ViewBag.PageRange && i <= Model.PageIndex + ViewBag.PageRange)
                    {
                                <li class="page-item">
                                    @if (i == Model.PageIndex)
                        {
                                        <span class="page-link">
                                            @i
                                            <span class="sr-only">(current)</span>
                                        </span>
                                    }
                                    else
                                    {
                                        <a class="page-link"
                                           href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=i, currentFilter=ViewData["CurrentFilter"], pageSize = ViewData["CurrentSize"] })">@i</a>
                                    }
                                </li>
                            }
                        }
                        <li class="page-item @nextDisabled">
                            <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.PageIndex + 1 > Model.TotalPages ? Model.TotalPages : Model.PageIndex + 1), currentFilter=ViewData["CurrentFilter"], pageSize = ViewData["CurrentSize"] })"
                               class="page-link" style="background-color:@nextBgDisabled">></a>
                        <li class="page-item @nextDisabled">
                            <a href="@Url.Action("Index", "CategoryManagement", new { sortOrder=ViewData["CurrentSort"], page=(Model.TotalPages), currentFilter=ViewData["CurrentFilter"], pageSize = ViewData["CurrentSize"] })"
                               class="page-link" style="background-color:@nextBgDisabled">>></a>
                    </ul>
                </nav>
            </div>
        </div>
                            }

</div>
@section Scripts {
    <script>
        function gettoken() {
            var token = '@Html.AntiForgeryToken()';
            token = $(token).val();
            return token;
        }

        function DeleteCategory(id) {
            $.confirm({
                title: 'Delete Confirm!',
                content: 'Are you sure to delete this category?',
                buttons: {
                    confirm: function () {
                        $.ajax({
                            type: "POST",
                            url: "@Url.Action("DeleteCategory", "CategoryManagement", new { area = "Admin" })",
                            data: {
                                __RequestVerificationToken: gettoken(),
                                Id: id,
                            },
                            success: function (result) {
                                $.alert({
                                    title: 'Alert!',
                                    content: result,
                                    buttons: {
                                        ok: function () {
                                            location.reload();
                                        }
                                    }
                                });
                            },
                            error: function (result) {
                                $.alert(result);
                                location.reload();
                            }
                        });
                    },
                    cancel: function () {
                    }
                }
            });
         }


    </script>
}