FA.JustBlog/Areas/Admin/Controllers/UserAdminController.cs
using FA.JustBlog.Areas.Admin.ViewModels;
using FA.JustBlog.Core.Models;
using FA.JustBlog.ViewModels;
using Microsoft.AspNet.Identity.Owin;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Authorize(Roles = "Administrators")]
    public class UsersAdminController : Controller
    {
        public UsersAdminController()
        {
        }

        public UsersAdminController(ApplicationUserManager userManager, ApplicationRoleManager roleManager)
        {
            UserManager = userManager;
            RoleManager = roleManager;
        }

        private ApplicationUserManager _userManager;
        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        private ApplicationRoleManager _roleManager;
        public ApplicationRoleManager RoleManager
        {
            get
            {
                return _roleManager ?? HttpContext.GetOwinContext().Get<ApplicationRoleManager>();
            }
            private set
            {
                _roleManager = value;
            }
        }

        //
        // GET: /Users/
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            return View(await UserManager.Users.ToListAsync());
        }

        //
        // GET: /Users/Details/5
        [HttpGet]
        public async Task<ActionResult> Details(int id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);

            ViewBag.RoleNames = await UserManager.GetRolesAsync(user.Id);

            return View(user);
        }

        //
        // GET: /Users/Create
        [HttpGet]
        public async Task<ActionResult> Create()
        {
            //Get the list of Roles
            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
            return View();
        }

        //
        // POST: /Users/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RegisterViewModel userViewModel, params string[] selectedRoles)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = userViewModel.Email, Email = userViewModel.Email };
                var adminresult = await UserManager.CreateAsync(user, userViewModel.Password);

                //Add User to the selected Roles 
                if (adminresult.Succeeded)
                {
                    if (selectedRoles != null)
                    {
                        var result = await UserManager.AddToRolesAsync(user.Id, selectedRoles);
                        if (!result.Succeeded)
                        {
                            ModelState.AddModelError("", result.Errors.First());
                            ViewBag.RoleId = new SelectList(await RoleManager.Roles.ToListAsync(), "Name", "Name");
                            return View();
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError("", adminresult.Errors.First());
                    ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
                    return View();

                }
                return RedirectToAction("Index");
            }
            ViewBag.RoleId = new SelectList(RoleManager.Roles, "Name", "Name");
            return View();
        }

        //
        // GET: /Users/Edit/1
        [HttpGet]
        public async Task<ActionResult> Edit(int id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }

            var userRoles = await UserManager.GetRolesAsync(user.Id);

            return View(new EditUserViewModel()
            {
                Id = user.Id,
                Email = user.Email,
                RolesList = RoleManager.Roles.ToList().Select(x => new SelectListItem()
                {
                    Selected = userRoles.Contains(x.Name),
                    Text = x.Name,
                    Value = x.Name
                }),
                Name = user.FullName,
                City = user.City,
                Address = user.Address,
                BirthDate = user.BirthDate
            });
        }

        //
        // POST: /Users/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Email,Id,Name,City,Address,BirthDate")] EditUserViewModel editUser, params string[] selectedRole)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByIdAsync(editUser.Id);
                if (user == null)
                {
                    return HttpNotFound();
                }

                user.UserName = editUser.Email;
                user.Email = editUser.Email;
                user.FullName = editUser.Name;
                user.City = editUser.City;
                user.Address = editUser.Address;
                user.BirthDate = editUser.BirthDate;
                var userRoles = await UserManager.GetRolesAsync(user.Id);

                selectedRole = selectedRole ?? new string[] { };

                var result = await UserManager.AddToRolesAsync(user.Id, selectedRole.Except(userRoles).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                result = await UserManager.RemoveFromRolesAsync(user.Id, userRoles.Except(selectedRole).ToArray<string>());

                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            ModelState.AddModelError("", "Something failed.");
            return View();
        }

        //
        // GET: /Users/Delete/5
        [HttpGet]
        public async Task<ActionResult> Delete(int id)
        {
            if (id <= 0)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var user = await UserManager.FindByIdAsync(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /Users/Delete/5
        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            if (ModelState.IsValid)
            {
                if (id <= 0)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                var user = await UserManager.FindByIdAsync(id);
                if (user == null)
                {
                    return HttpNotFound();
                }
                var result = await UserManager.DeleteAsync(user);
                if (!result.Succeeded)
                {
                    ModelState.AddModelError("", result.Errors.First());
                    return View();
                }
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

FA.JustBlog/Controllers/CategoryController.cs
using FA.JustBlog.Core.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FA.JustBlog.Controllers
{
    public class CategoryController : Controller
    {
        private ICatgoryService _categoryService;

        public CategoryController(ICatgoryService categoryService)
        {
            _categoryService = categoryService;
        }

        [ChildActionOnly]
        public ActionResult GetMenuCategory()
        {
            var response = _categoryService.GetAll();

            if (response.Status == 200)
            {
                return PartialView("_MenuCategory", response.Data);
            }
            else
            {
                return PartialView("_MenuCategory", null);
            }
        }
    }
}

FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Core.Common;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Service;
using FA.JustBlog.Models;
using FA.JustBlog.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FA.JustBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;

        public PostController(IPostService postService)
        {
            _postService = postService;
        }
        // GET: Post
        public async Task<ActionResult> Index(string byWhat, string currentByWhat, string currentFilter, string searchString, int? page, int? pageSize)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            if (string.IsNullOrEmpty(byWhat))
            {
                byWhat = currentByWhat;
            }
            ViewData["CurrentByWhat"] = byWhat;

            Expression<Func<Post, bool>> filter = null;
            Func<IQueryable<Post>, IOrderedQueryable<Post>> orderBy = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = b => b.Title.Contains(searchString) && b.PostContent.Contains(searchString);
            }
            if(orderBy == null)
            {
                orderBy = b => b.OrderByDescending(x => x.ViewCount);
            }
            var response = await _postService.GetPublishedAsyncPagination(filter: filter, orderBy: orderBy, page: page ?? 1, pageSize: pageSize ?? 4);

            if (response.Status == 200)
            {
                ListPostViewModel data = new ListPostViewModel()
                {
                    ListPost = response.Data as PaginationList<Post>,
                    Type = Common.ListPostTypeToIndex.AllPost
                };

                return View(data);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public ActionResult LatestPostsinside()
        {
            var response = _postService.GetLatestPost(5);

            if (response.Status == 200)
            {
                var list = response.Data as List<Post>;
                ListPostModel result = new ListPostModel()
                {
                    ListPost = list.Where(p => p.Published).ToList(),
                    Type = TypeListPostEnum.LatestPost
                };
                return PartialView("_ListPosts", result);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public ActionResult MostViewedPosts()
        {
            var response = _postService.GetMostViewedPost(5);

            if (response.Status == 200)
            {
                var list = response.Data as List<Post>;
                ListPostModel result = new ListPostModel()
                {
                    ListPost = list.Where(p => p.Published).ToList(),
                    Type = TypeListPostEnum.MostViewPost
                };
                return PartialView("_ListPosts", result);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public ActionResult DetailPost(int year, int month, string title)
        {
            var response = _postService.GetDetail(year, month, title);

            if (response.Status == 200)
            {
                Post post = response.Data as Post;
                ViewBag.Comments = post.Comments;
                return View(post);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public async Task<ActionResult> ListPostByCategory(string byWhat, string currentByWhat, string currentFilter, string searchString, int? page, int? pageSize)
        {
            if (searchString != null)
            {
                page = 1;
                byWhat = currentByWhat;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            if (string.IsNullOrEmpty(byWhat))
            {
                byWhat = currentByWhat;
            }
            ViewData["CurrentByWhat"] = byWhat;

            Expression<Func<Post, bool>> filter = null;
            Func<IQueryable<Post>, IOrderedQueryable<Post>> orderBy = null;
            Expression<Func<Post, bool>> filterByUser = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = b => b.Title.Contains(searchString) && b.PostContent.Contains(searchString);
            }
            if (orderBy == null)
            {
                orderBy = b => b.OrderByDescending(x => x.ViewCount);
            }
            if(filterByUser == null)
            {
                filterByUser= b => b.Category.Name.Contains(byWhat);
            }
            var response = await _postService.GetPublishedAsyncPagination(filter: filter, filterByUser: filterByUser, orderBy: orderBy, page: page ?? 1, pageSize: pageSize ?? 4);

            if (response.Status == 200)
            {
                ListPostViewModel data = new ListPostViewModel()
                {
                    ListPost = response.Data as PaginationList<Post>,
                    Type = Common.ListPostTypeToIndex.ByCategory,
                    ByWhat = byWhat
                };

                return View("Index", data);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public async Task<ActionResult> GetPostsByTag(string byWhat, string currentByWhat, string currentFilter, string searchString, int? page, int? pageSize)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            if (string.IsNullOrEmpty(byWhat))
            {
                byWhat = currentByWhat;
            }
            ViewData["CurrentByWhat"] = byWhat;

            Expression<Func<Post, bool>> filter = null;
            Func<IQueryable<Post>, IOrderedQueryable<Post>> orderBy = null;
            Expression<Func<Post, bool>> filterByUser = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = b => b.Title.Contains(searchString) && b.PostContent.Contains(searchString);
            }
            if (orderBy == null)
            {
                orderBy = b => b.OrderByDescending(x => x.ViewCount);
            }
            if (filterByUser == null)
            {
                filterByUser = b => b.Tags.Any(t => t.Name.Contains(byWhat));
            }
            var response = await _postService.GetPublishedAsyncPagination(filter: filter, filterByUser: filterByUser, orderBy: orderBy, page: page ?? 1, pageSize: pageSize ?? 4);

            if (response.Status == 200)
            {
                ListPostViewModel data = new ListPostViewModel()
                {
                    ListPost = response.Data as PaginationList<Post>,
                    Type = Common.ListPostTypeToIndex.ByTag,
                    ByWhat = byWhat
                };

                return View("Index",data);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }
    }
}

FA.JustBlog/Controllers/TagController.cs
using FA.JustBlog.Core.Service;
using System.Web.Mvc;

namespace FA.JustBlog.Controllers
{
    public class TagController : Controller
    {
        private readonly ITagService _tagService;

        public TagController(ITagService tagService)
        {
            _tagService = tagService;
        }

        [ChildActionOnly]
        public ActionResult PopularTags()
        {
            var popularTags = _tagService.GetPopularTags(10).Data;

            return PartialView("_PopularTags", popularTags);
        }
    }
}

FA.JustBlog/Views/Shared/_CustomLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Bait's Blog</title>
    <!-- CSS -->
    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/fontawesome-free")
    <!-- Custom fonts for this template -->
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
        <div class="container">
            <a class="navbar-brand" href="@Url.Action("Index", "Post")">Blog</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                Menu
                <i class="fas fa-bars"></i>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-5">
                    <li class="nav-item">
                        <a class="nav-link" href="@Url.Action("Index", "Post")">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="#">About</a>
                    </li>
                    @Html.Action("GetMenuCategory", "Category")
                    <li class="nav-item">
                        <a class="nav-link" href="#">Contact</a>
                    </li>
                       
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>

    <!-- Page Header -->
    <header class="masthead" style="background-image: url(/Assets/images/home-bg.jpg);
                                                        background-repeat: no-repeat;
                                                        background-size: 100% auto;">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-md-10 mx-auto">
                    <div class="site-heading">
                        <h1>Bait's Blog</h1>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <!-- Main Content -->
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-9 mx-auto">
                @RenderBody()
            </div>
            <div class="col-lg-3 mx-auto">
                @Html.Action("AboutCard", "Home")
                @Html.Action("MostViewedPosts", "Post")
                <hr />
                @Html.Action("LatestPostsinside", "Post")
                <hr />
                @Html.Action("PopularTags", "Tag")
            </div>
        </div>

        <hr />
        @Html.Partial("_PartialFooter")
    </div>

    <!-- Bootstrap core JavaScript -->
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/js")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

FA.JustBlog/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="@Url.Action("Index", "Home", new { area = "" })">
            <img src="~/Assets/images/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
            Bootstrap
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "Post", new { area = "" })">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("About", "Home", new { area = "" })">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Contact", "Home", new { area = "" })">Contact</a>
                </li>
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin Dashboard
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Index", "UsersAdmin", new { area = "Identity" })">Users Admin</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "RolesAdmin", new { area = "Identity" })">Roles Admin</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Manager</a>
                        </div>
                    </li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <h1>Left Menu</h1>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FA.JustBlog/Views/Shared/_PartialFooter.cshtml
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-md-10 mx-auto">
                <ul class="list-inline text-center">
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-facebook-f fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                    <li class="list-inline-item">
                        <a href="#">
                            <span class="fa-stack fa-lg">
                                <i class="fa fa-circle fa-stack-2x"></i>
                                <i class="fa fa-github fa-stack-1x fa-inverse"></i>
                            </span>
                        </a>
                    </li>
                </ul>
                <p class="copyright text-muted">Copyright &copy; Your Website 2019</p>
            </div>
        </div>
    </div>
</footer>