FA.JustBlog/Areas/Admin/Controllers/DashboardController.cs
using FA.JustBlog.Areas.Admin.ViewModels;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace FA.JustBlog.Areas.Admin.Controllers
{
    [Authorize(Roles = "Contributor")]
    public class DashboardController : Controller
    {
        private readonly IPostService _postService;
        private readonly ICatgoryService _categoryService;

        public DashboardController(IPostService postService, ICatgoryService categoryService)
        {
            _postService = postService;
            _categoryService = categoryService;
        }
        public ActionResult Index()
        {
            var publishedPost = _postService.GetPublisedPosts().Data as List<Post>;
            var unPublishedPost = _postService.GetUnpublisedPosts().Data as List<Post>;
            var totalPost = _postService.GetAll().Data as List<Post>;

            string userName = User.Identity.Name;
            DashboardViewModel data = new DashboardViewModel();
            if (publishedPost.Any() && publishedPost != null)
            {
                data.PublishedCount = User.IsInRole("Contributor") && !User.IsInRole("Administrators") ? publishedPost.Where(x => x.CreatedBy.Trim() == userName).Count() : publishedPost.Count();
            }
            if (unPublishedPost.Any() && unPublishedPost != null)
            {
                data.UnPublishedCount = User.IsInRole("Contributor") && !User.IsInRole("Administrators") ? unPublishedPost.Where(x => x.CreatedBy.Trim() == userName).Count() : unPublishedPost.Count();
            }
            if (totalPost.Any() && totalPost != null)
            {
                data.TotalPost = User.IsInRole("Contributor") && !User.IsInRole("Administrators") ? totalPost.Where(x => x.CreatedBy.Trim() == userName).Count() : totalPost.Count();
            }

            return View(data);
        }

        public JsonResult GetPostForChart()
        {
            var responseCate = _categoryService.GetAll();
            if(responseCate.Status == 200)
            {
                List<Category> listCate = responseCate.Data as List<Category>;
                List<CategoryChart> DataChart = new List<CategoryChart>();
                foreach(Category cate in listCate)
                {
                    int countPost = Convert.ToInt32(_postService.CountPostsForCategory(cate.Name).Data);
                    DataChart.Add(new CategoryChart()
                    {
                        Category = cate.Name,
                        CountPost = countPost
                    });
                }

                return Json(DataChart, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(null, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

FA.JustBlog/Controllers/PostController.cs
using FA.JustBlog.Core.Common;
using FA.JustBlog.Core.Models;
using FA.JustBlog.Core.Service;
using FA.JustBlog.Models;
using FA.JustBlog.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace FA.JustBlog.Controllers
{
    public class PostController : Controller
    {
        private readonly IPostService _postService;

        public PostController(IPostService postService)
        {
            _postService = postService;
        }
        // GET: Post
        public async Task<ActionResult> Index(string byWhat, string currentByWhat, string currentFilter, string searchString, int? page, int? pageSize)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            if (string.IsNullOrEmpty(byWhat))
            {
                byWhat = currentByWhat;
            }
            ViewData["CurrentByWhat"] = byWhat;

            Expression<Func<Post, bool>> filter = null;
            Func<IQueryable<Post>, IOrderedQueryable<Post>> orderBy = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = b => b.Title.Contains(searchString) && b.PostContent.Contains(searchString);
            }
            if(orderBy == null)
            {
                orderBy = b => b.OrderByDescending(x => x.ViewCount);
            }
            var response = await _postService.GetPublishedAsyncPagination(filter: filter, orderBy: orderBy, page: page ?? 1, pageSize: pageSize ?? 4);

            if (response.Status == 200)
            {
                ListPostViewModel data = new ListPostViewModel()
                {
                    ListPost = response.Data as PaginationList<Post>,
                    Type = Common.ListPostTypeToIndex.AllPost
                };

                return View(data);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public ActionResult LatestPostsinside()
        {
            var response = _postService.GetLatestPost(5);

            if (response.Status == 200)
            {
                var list = response.Data as List<Post>;
                ListPostModel result = new ListPostModel()
                {
                    ListPost = list.Where(p => p.Published).ToList(),
                    Type = TypeListPostEnum.LatestPost
                };
                return PartialView("_ListPosts", result);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public ActionResult MostViewedPosts()
        {
            var response = _postService.GetMostViewedPost(5);

            if (response.Status == 200)
            {
                var list = response.Data as List<Post>;
                ListPostModel result = new ListPostModel()
                {
                    ListPost = list.Where(p => p.Published).ToList(),
                    Type = TypeListPostEnum.MostViewPost
                };
                return PartialView("_ListPosts", result);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public ActionResult DetailPost(int year, int month, string title)
        {
            var response = _postService.GetDetail(year, month, title);

            if (response.Status == 200)
            {
                Post post = response.Data as Post;
                ViewBag.Comments = post.Comments;
                return View(post);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public async Task<ActionResult> ListPostByCategory(string byWhat, string currentByWhat, string currentFilter, string searchString, int? page, int? pageSize)
        {
            if (searchString != null)
            {
                page = 1;
                byWhat = currentByWhat;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            if (string.IsNullOrEmpty(byWhat))
            {
                byWhat = currentByWhat;
            }
            ViewData["CurrentByWhat"] = byWhat;

            Expression<Func<Post, bool>> filter = null;
            Func<IQueryable<Post>, IOrderedQueryable<Post>> orderBy = null;
            Expression<Func<Post, bool>> filterByUser = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = b => b.Title.Contains(searchString) && b.PostContent.Contains(searchString);
            }
            if (orderBy == null)
            {
                orderBy = b => b.OrderByDescending(x => x.ViewCount);
            }
            if(filterByUser == null)
            {
                filterByUser= b => b.Category.Name.Contains(byWhat);
            }
            var response = await _postService.GetPublishedAsyncPagination(filter: filter, filterByUser: filterByUser, orderBy: orderBy, page: page ?? 1, pageSize: pageSize ?? 4);

            if (response.Status == 200)
            {
                ListPostViewModel data = new ListPostViewModel()
                {
                    ListPost = response.Data as PaginationList<Post>,
                    Type = Common.ListPostTypeToIndex.ByCategory,
                    ByWhat = byWhat
                };

                return View("Index", data);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }

        public async Task<ActionResult> GetPostsByTag(string byWhat, string currentByWhat, string currentFilter, string searchString, int? page, int? pageSize)
        {
            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewData["CurrentFilter"] = searchString;

            if (string.IsNullOrEmpty(byWhat))
            {
                byWhat = currentByWhat;
            }
            ViewData["CurrentByWhat"] = byWhat;

            Expression<Func<Post, bool>> filter = null;
            Func<IQueryable<Post>, IOrderedQueryable<Post>> orderBy = null;
            Expression<Func<Post, bool>> filterByUser = null;

            if (!string.IsNullOrEmpty(searchString))
            {
                filter = b => b.Title.Contains(searchString) && b.PostContent.Contains(searchString);
            }
            if (orderBy == null)
            {
                orderBy = b => b.OrderByDescending(x => x.ViewCount);
            }
            if (filterByUser == null)
            {
                filterByUser = b => b.Tags.Any(t => t.Name.Contains(byWhat));
            }
            var response = await _postService.GetPublishedAsyncPagination(filter: filter, filterByUser: filterByUser, orderBy: orderBy, page: page ?? 1, pageSize: pageSize ?? 4);

            if (response.Status == 200)
            {
                ListPostViewModel data = new ListPostViewModel()
                {
                    ListPost = response.Data as PaginationList<Post>,
                    Type = Common.ListPostTypeToIndex.ByTag,
                    ByWhat = byWhat
                };

                return View("Index",data);
            }
            else
            {
                return HttpNotFound(response.MessageText);
            }
        }
    }
}

FA.JustBlog/Areas/Admin/Views/Shared/_DashboardLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>AdminLTE | Dashboard</title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <link href="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/css/select2.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

    @Styles.Render("~/Content/css")
    @Styles.Render("~/bundles/fontawesome-free")


    <!-- Google Font -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="">

        <header class="main-header">
            <!-- Logo -->
            <a href="@Url.Action("Index", "Dashboard")" class="logo">
                <!-- mini logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>AD</b></span>
                <!-- logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Admin</b></span>
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>

                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <img src="~/Assets/images/user2-160x160.jpg" class="user-image" alt="User Image">
                                <span class="hidden-xs">@User.Identity.Name</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="~/Assets/images/user2-160x160.jpg" class="img-circle" alt="User Image">
                                    <p>
                                        @User.Identity.Name - Web Developer
                                    </p>
                                </li>

                                <!-- Menu Footer-->

                                <li class="user-footer">
                                    @using (Html.BeginForm("LogOff", "Account", new { area = "" }, FormMethod.Post, new { id = "logoutForm", @class = "navbar-right" }))
                                    {
                                        @Html.AntiForgeryToken()
                                        <div class="row">
                                            <a href="@Url.Action("Details", "UsersAdmin", new {area = "Admin", Id = User.Identity.GetUserId()})" class="btn btn-default btn-flat">Profile</a>
                                            <a class="btn btn-default btn-flat" href="javascript:document.getElementById('logoutForm').submit()">Sign out</a>
                                        </div>    
                                    }
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <!-- Left side column. contains the logo and sidebar -->
        <aside class="main-sidebar">
            <!-- sidebar: style can be found in sidebar.less -->
            <section class="sidebar">
                <!-- sidebar menu: : style can be found in sidebar.less -->
                <ul class="sidebar-menu" data-widget="tree">
                    <li class="header">MAIN NAVIGATION</li>
                    <li class="active treeview">
                        <a href="#">
                            <i class="fa fa-tasks"></i> <span>Blog Management</span>
                            <span class="pull-right-container">
                                <i class="fa fa-angle-left pull-right"></i>
                            </span>
                        </a>
                        <ul class="treeview-menu">
                            <li class="active"><a href="@Url.Action("ListPost","PostManagement", new { area = "Admin" })"><i class="fa fa-circle-o"></i> Posts Management</a></li>
                            <li><a href="@Url.Action("Index","CategoryManagement", new { area = "Admin" })"><i class="fa fa-circle-o"></i> Categories Management</a></li>
                            <li><a href="@Url.Action("Index","TagsManagement", new { area = "Admin" })"><i class="fa fa-circle-o"></i> Tags Management</a></li>
                            <li><a href="@Url.Action("Index","CommentsManagement", new { area = "Admin" })"><i class="fa fa-circle-o"></i> Comments Management</a></li>
                        </ul>
                    </li>
                    @if (User.IsInRole("Administrators"))
                    {
                        <li class="active treeview">
                            <a href="#">
                                <i class="fa fa-user"></i> <span>User Management</span>
                                <span class="pull-right-container">
                                    <i class="fa fa-angle-left pull-right"></i>
                                </span>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="@Url.Action("Index","UsersAdmin", new { area = "Admin" })"><i class="fa fa-circle-o"></i>User</a></li>
                                <li><a href="@Url.Action("Index","RolesAdmin", new { area = "Admin" })"><i class="fa fa-circle-o"></i>Role</a></li>
                            </ul>
                        </li>
                    }
                    <li>
                        <a href="@Url.Action("Index","Post",new { area = "" })">Back To Home</a>
                    </li>
                </ul>
            </section>
            <!-- /.sidebar -->
        </aside>

        <div class="content-wrapper">
            @RenderBody()
        </div>
    </div>
    @*<script>
            $.widget.bridge('uibutton', $.ui.button);
        </script>*@

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/js")
    <script src="https://cdn.jsdelivr.net/npm/select2@4.0.13/dist/js/select2.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <script src="https://cdn.ckeditor.com/4.14.0/standard/ckeditor.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

FA.JustBlog/Areas/Admin/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="@Url.Action("Index", "Home", new { area = "" })">
            <img src="~/Assets/images/bootstrap-solid.svg" width="30" height="30" class="d-inline-block align-top" alt="">
            Bootstrap
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="@Url.Action("Index", "Home", new { area = "" })">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("About", "Home", new { area = "" })">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Contact", "Home", new { area = "" })">Contact</a>
                </li>
                @if (Request.IsAuthenticated && User.IsInRole("Admin"))
                {
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Admin Dashboard
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="@Url.Action("Index", "UsersAdmin", new { area = "Identity" })">Users Admin</a>
                            <a class="dropdown-item" href="@Url.Action("Index", "RolesAdmin", new { area = "Identity" })">Roles Admin</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Manager</a>
                        </div>
                    </li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>

    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <h1>Left Menu</h1>
            </div>
            <div class="col-md-9">
                @RenderBody()
            </div>
        </div>
    </div>

    <footer>
        <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
    </footer>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>